# Generated by Django 5.1.1 on 2024-10-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.IntegerField(choices=[(0, 'Absent'), (1, 'Present')], default=0),
        ),
    ]
