# Generated by Django 5.1.1 on 2024-10-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.IntegerField(choices=[(1, 'Present'), (0, 'Absent')]),
        ),
    ]
